//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days,day,d.
        /// </summary>
        internal static string TimeSpanDayStrings {
            get {
                return ResourceManager.GetString("TimeSpanDayStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dhmst.
        /// </summary>
        internal static string TimeSpanFullBuildOrder {
            get {
                return ResourceManager.GetString("TimeSpanFullBuildOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours,hour,hrs,hr,h.
        /// </summary>
        internal static string TimeSpanHourStrings {
            get {
                return ResourceManager.GetString("TimeSpanHourStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        internal static string TimeSpanManyDayFormat {
            get {
                return ResourceManager.GetString("TimeSpanManyDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        internal static string TimeSpanManyHourFormat {
            get {
                return ResourceManager.GetString("TimeSpanManyHourFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} milliseconds.
        /// </summary>
        internal static string TimeSpanManyMillisecondFormat {
            get {
                return ResourceManager.GetString("TimeSpanManyMillisecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string TimeSpanManyMinuteFormat {
            get {
                return ResourceManager.GetString("TimeSpanManyMinuteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        internal static string TimeSpanManySecondFormat {
            get {
                return ResourceManager.GetString("TimeSpanManySecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds,millisecond,ms.
        /// </summary>
        internal static string TimeSpanMillisecondStrings {
            get {
                return ResourceManager.GetString("TimeSpanMillisecondStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes,minute,mins,min,m.
        /// </summary>
        internal static string TimeSpanMinuteStrings {
            get {
                return ResourceManager.GetString("TimeSpanMinuteStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day.
        /// </summary>
        internal static string TimeSpanOneDayFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneDayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour.
        /// </summary>
        internal static string TimeSpanOneHourFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneHourFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} millisecond.
        /// </summary>
        internal static string TimeSpanOneMillisecondFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneMillisecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string TimeSpanOneMinuteFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneMinuteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        internal static string TimeSpanOneSecondFormat {
            get {
                return ResourceManager.GetString("TimeSpanOneSecondFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s*(?:(?&lt;d&gt;\d+)\s*d\s*[,]?\s*)?(?:(?&lt;h&gt;\d+)\s*h\s*[,]?\s*)?(?:(?&lt;m&gt;\d+)\s*m\s*[,]?\s*)?(?:(?&lt;s&gt;\d+)\s*s\s*[,]?\s*)?(?:(?&lt;t&gt;\d+)\s*t)?\s*.
        /// </summary>
        internal static string TimeSpanParseRegEx {
            get {
                return ResourceManager.GetString("TimeSpanParseRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds,second,secs,sec,s.
        /// </summary>
        internal static string TimeSpanSecondStrings {
            get {
                return ResourceManager.GetString("TimeSpanSecondStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string TimeSpanSeparator {
            get {
                return ResourceManager.GetString("TimeSpanSeparator", resourceCulture);
            }
        }
    }
}
